name=input("Enter your name: ")
hobby=input("Enter your hobby: ")
print("\n---Welcome Message---")
print(f"Hello {name}")
print("Welcome to the world of python programming!")
print(f"It's great to know that you love {hobby}.")
print("Get ready to build something amazing today.")
